============================ Start Error ========================================================
Time : 12:47:39 PM

Error : The underlying connection was closed: An unexpected error occurred on a receive.

StackTrace  :    at WPS.Models.WPSServiceModel.checkDuplicateCompanyByAgent(Int32 SaleAccountId, String EstID) in G:\Siraj Finance\WPS\WPS\Models\WPSServiceModel.cs:line 162
   at WPS.Controllers.CompanyController.UploadFile(Nullable`1 user, Nullable`1 OrgId, Nullable`1 CompanyId, ImportCompanyExcel model) in G:\Siraj Finance\WPS\WPS\Controllers\CompanyController.cs:line 466

TargetSite   : Int32 checkDuplicateCompanyByAgent(Int32, System.String)
Line No.  :162
============================= End Error =========================================================


============================ Start Error ========================================================
Time : 12:58:27 PM

Error : The underlying connection was closed: An unexpected error occurred on a receive.

StackTrace  :    at WPS.Models.WPSServiceModel.checkDuplicateCompanyByAgent(Int32 SaleAccountId, String EstID) in G:\Siraj Finance\WPS\WPS\Models\WPSServiceModel.cs:line 162
   at WPS.Controllers.CompanyController.UploadFile(Nullable`1 user, Nullable`1 OrgId, Nullable`1 CompanyId, ImportCompanyExcel model) in G:\Siraj Finance\WPS\WPS\Controllers\CompanyController.cs:line 466

TargetSite   : Int32 checkDuplicateCompanyByAgent(Int32, System.String)
Line No.  :162
============================= End Error =========================================================


============================ Start Error ========================================================
Time : 1:22:00 PM

The process cannot access the file 'G:\Siraj Finance\WPS\WPS\LogFiles\Company Upload By 1 - 28-Mar-2019.txt' because it is being used by another process.

   at WPS.Log.LogWrite(String msg, String fileName, Exception ex)
   at WPS.Controllers.CompanyController.UploadFile(Nullable`1 user, Nullable`1 OrgId, Nullable`1 CompanyId, ImportCompanyExcel model)

Void LogWrite(System.String, System.String, System.Exception)
Line No.  :0
============================= End Error =========================================================


============================ Start Error ========================================================
Time : 1:33:00 PM

Error : Object reference not set to an instance of an object.

StackTrace  :    at WPS.Log.LogWrite(String msg, String fileName, Exception ex) in G:\Siraj Finance\WPS\WPS\GlobalObject\Log.cs:line 66
   at WPS.Controllers.CompanyController.UploadFile(Nullable`1 user, Nullable`1 OrgId, Nullable`1 CompanyId, ImportCompanyExcel model) in G:\Siraj Finance\WPS\WPS\Controllers\CompanyController.cs:line 418

TargetSite   : Void LogWrite(System.String, System.String, System.Exception)
Line No.  :66
============================= End Error =========================================================


